### ISSUE TITLE
What do you mean by insecure?

### ISSUE THREAD

**Issue by NoamDev** [stevenengler/witness-encryption#1]
Hi! Thanks for creating this library, seems very interesting.
Could you explain what do you mean when saying the library is insecure?

**Comment by alex-norton** [comment]
A secure witness encryption implementation would have guarantees that anyone who can decrypt the message must know the witness. This implementation does not have those guarantees, as the underlying encryption scheme it's based on has known attacks against it. It shouldn't be used for any serious application. :)
